### ISSUE TITLE
Doesn't work on JRuby 9.0.0.0

### ISSUE THREAD

**Issue by kevgo** [charlierudolph/cucumber_lint#14]
I'm not implying that it necessarily should run on that platform. Just putting this on your radar so that there is a single place to talk about this. Here is the stacktrace:

```
gherkin/formatter/PrettyFormatter.java:293:in `prepareTable': java.lang.ClassCastException: org.jruby.RubyObject cannot be cast to gherkin.formatter.model.Row
    from gherkin/formatter/PrettyFormatter.java:279:in `table'
    from java/lang/reflect/Method.java:497:in `invoke'
```

**Comment by charlierudolph** [comment]
I noticed nucleus is not longer using jruby. Do you think this is still worth supporting?

**Comment by kevgo** [comment]
No urgent need. JRuby is a lot more for edge use cases than I thought initially.
